//! GeoJSON layer response DTOs shared between the area-data and
//! land-price endpoints.

use serde::Serialize;
use terrasight_geo::coord::GeoCoord;
use terrasight_geo::spatial::point_to_polygon;

use crate::domain::model::{LayerResult, LayerType};

pub use terrasight_server::http::response::FeatureDto;

/// GeoJSON `FeatureCollection` augmented with truncation metadata.
///
/// Returned by the area-data and land-prices handlers so that MapLibre GL
/// clients can detect when the server has capped the result set and prompt
/// the user to zoom in for a complete view.
#[derive(Debug, Serialize)]
pub struct LayerResponseDto {
    /// GeoJSON type discriminator. Always `"FeatureCollection"`.
    pub r#type: String,
    /// Array of GeoJSON `Feature` objects for this layer.
    pub features: Vec<FeatureDto>,
    /// `true` when the repository applied the per-layer limit and there are
    /// more records beyond what is returned.
    pub truncated: bool,
    /// Number of features in `features` (after any truncation).
    pub count: usize,
    /// The maximum feature count that was enforced for this layer at the
    /// requested zoom level.
    pub limit: i64,
}

impl LayerResponseDto {
    /// Construct from a feature list and truncation metadata.
    pub fn new(features: Vec<FeatureDto>, truncated: bool, limit: i64) -> Self {
        let count = features.len();
        Self {
            r#type: "FeatureCollection".to_string(),
            features,
            truncated,
            count,
            limit,
        }
    }

    /// Construct a [`LayerResponseDto`] from a domain [`LayerResult`] for the
    /// given [`LayerType`]. Point features belonging to the `LandPrice` layer
    /// are converted into ~30 m² polygon squares for better map visibility.
    pub fn from_layer_result(result: LayerResult, layer: LayerType) -> Self {
        let features: Vec<FeatureDto> = result
            .features
            .into_iter()
            .map(geo_feature_to_dto)
            .map(|f| match layer {
                LayerType::LandPrice => point_feature_to_polygon_owned(f),
                _ => f,
            })
            .collect();

        Self::new(features, result.truncated, result.limit)
    }
}

/// Extract `(longitude, latitude)` from a GeoJSON Point feature's coordinates.
///
/// Returns `None` if the coordinates array is missing or cannot be parsed as two
/// finite `f64` values.
fn extract_point_coords(feature: &FeatureDto) -> Option<(f64, f64)> {
    let coords = feature.geometry.coordinates.as_array()?;
    let lng = coords.first()?.as_f64()?;
    let lat = coords.get(1)?.as_f64()?;
    Some((lng, lat))
}

/// Convert a `Point` geometry inside a [`FeatureDto`] to a small `Polygon` square.
///
/// Land price data is stored as point geometries. For better visual discoverability
/// on a MapLibre GL map (especially at higher zoom levels), each point is replaced
/// with a ~30m × 30m square polygon generated by [`point_to_polygon`].
///
/// If the feature's geometry type is not `"Point"`, or if the coordinate array
/// cannot be parsed as `[lng, lat]`, the feature is returned unchanged.
pub fn point_feature_to_polygon_owned(mut feature: FeatureDto) -> FeatureDto {
    if feature.geometry.r#type != "Point" {
        return feature;
    }

    let Some((lng, lat)) = extract_point_coords(&feature) else {
        return feature;
    };

    let ring = point_to_polygon(&GeoCoord { lng, lat });
    // GeoJSON Polygon coordinates: array of rings, each ring is array of [lng, lat] positions.
    let ring_json: Vec<serde_json::Value> = ring
        .iter()
        .map(|[x, y]| serde_json::json!([x, y]))
        .collect();

    feature.geometry.r#type = "Polygon".to_string();
    feature.geometry.coordinates = serde_json::json!([ring_json]);
    feature
}

/// Convert a domain [`GeoFeature`] to a [`FeatureDto`] for JSON serialization.
///
/// Bridges the domain entity to the lib's domain-independent DTO.
///
/// [`GeoFeature`]: crate::domain::model::GeoFeature
pub fn geo_feature_to_dto(f: crate::domain::model::GeoFeature) -> FeatureDto {
    FeatureDto::new(
        f.geometry.r#type.as_str().to_string(),
        f.geometry.coordinates,
        f.properties,
    )
}
