//! GeoJSON layer response DTOs shared between the area-data and
//! land-price endpoints.

use realestate_geo_math::spatial::point_to_polygon;
use serde::Serialize;

pub use realestate_api_core::response::{FeatureCollectionDto, FeatureDto};

/// GeoJSON FeatureCollection response with truncation metadata.
///
/// Returned by area-data and land-prices handlers so that MapLibre GL clients
/// can detect when the result has been capped and prompt the user to zoom in.
#[derive(Debug, Serialize)]
pub struct LayerResponseDto {
    /// Always `"FeatureCollection"`.
    pub r#type: String,
    pub features: Vec<FeatureDto>,
    /// `true` when the repository capped the result at `limit`.
    pub truncated: bool,
    /// Number of features actually returned (after truncation).
    pub count: usize,
    /// The per-layer limit that was applied.
    pub limit: i64,
}

impl LayerResponseDto {
    /// Construct from a feature list and truncation metadata.
    pub fn new(features: Vec<FeatureDto>, truncated: bool, limit: i64) -> Self {
        let count = features.len();
        Self {
            r#type: "FeatureCollection".to_string(),
            features,
            truncated,
            count,
            limit,
        }
    }
}

/// Convert a `Point` geometry inside a [`FeatureDto`] to a small `Polygon` square.
///
/// Land price data is stored as point geometries. For better visual discoverability
/// on a MapLibre GL map (especially at higher zoom levels), each point is replaced
/// with a ~30m × 30m square polygon generated by [`point_to_polygon`].
///
/// If the feature's geometry type is not `"Point"`, or if the coordinate array
/// cannot be parsed as `[lng, lat]`, the feature is left unchanged.
pub fn point_feature_to_polygon(feature: &mut FeatureDto) {
    if feature.geometry.r#type != "Point" {
        return;
    }

    // Coordinates for a Point are a JSON array [lng, lat].
    let coords = feature.geometry.coordinates.as_array();
    let (lng, lat) = match coords {
        Some(arr) if arr.len() >= 2 => {
            let lng = arr[0].as_f64();
            let lat = arr[1].as_f64();
            match (lng, lat) {
                (Some(lng), Some(lat)) => (lng, lat),
                _ => return,
            }
        }
        _ => return,
    };

    let ring = point_to_polygon(lng, lat);
    // GeoJSON Polygon coordinates: array of rings, each ring is array of [lng, lat] positions.
    let ring_json: Vec<serde_json::Value> = ring
        .iter()
        .map(|[x, y]| serde_json::json!([x, y]))
        .collect();

    feature.geometry.r#type = "Polygon".to_string();
    feature.geometry.coordinates = serde_json::json!([ring_json]);
}

/// Convert a domain [`GeoFeature`] to a [`FeatureDto`] for JSON serialization.
///
/// Bridges the domain entity to the lib's domain-independent DTO.
///
/// [`GeoFeature`]: crate::domain::entity::GeoFeature
pub fn geo_feature_to_dto(f: crate::domain::entity::GeoFeature) -> FeatureDto {
    FeatureDto::new(f.geometry.r#type, f.geometry.coordinates, f.properties)
}
